export const cuisineList = [
    "Ăn sáng",
    "Cà phê",
    "Quán nước",
    "Quán nhậu",
    "Đồ chay",
    "Món Hàn",
    "Món Thái",
    "Món Nhật",
    "Món Ấn",
    "Món Hoa",
    "Healthy",
    "Burgers",
    "BBQ",
    "Hotpot",
    "Buffet",
    "Steak",
    "Pizza",
]